# Generated by Django 5.2.6 on 2025-09-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
    ]
